schema: "classroom50/repo-config/v1"
classroom: "indprog"
assignment: "i-know-flowchart"
owner:
  username: "Tina245445"
  id: 253248356
  accepted_at: "2026-09-03T15:51:16Z"
source:
  owner: "geko-crooms"
  owner_id: 316422449
  repo: "i-know-flowchart"
  branch: "main"
